services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: doitpay
      POSTGRES_USER: doitpay
      POSTGRES_PASSWORD: doitpay
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U doitpay -d doitpay" ]
      interval: 5s
      timeout: 3s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10


  api:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: api
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doitpay
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: worker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doitpay
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 2