services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: doitpay
      POSTGRES_USER: doitpay
      POSTGRES_PASSWORD: doitpay
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"