spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doitpay
    username: doitpay
    password: doitpay
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  rabbitmq:
    host: localhost
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
        concurrency: 10
        max-concurrency: 20

---
spring:
  config:
    activate:
      on-profile: api
  rabbitmq:
    listener:
      simple:
        auto-startup: false

---
spring:
  config:
    activate:
      on-profile: worker
  main:
    web-application-type: none