CREATE TABLE merchants (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance         NUMERIC(19,2) NOT NULL CHECK (balance >= 0),
    account_number  VARCHAR(64)   NOT NULL,
    created_at      TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE TABLE transactions (
    transaction_id   UUID          PRIMARY KEY,
    merchant_id      BIGINT        NOT NULL REFERENCES merchants (id),
    amount           NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    destination_acct VARCHAR(64)   NOT NULL,
    status           VARCHAR(20)   NOT NULL
                                   CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    failure_reason   TEXT,
    created_at       TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE INDEX idx_transactions_status ON transactions (status);

INSERT INTO merchants (id, balance, account_number)
VALUES (1, 10000000.00, '0000000001');

SELECT setval(pg_get_serial_sequence('merchants', 'id'), 1, true);